<?php

namespace TicketBundle\Repository;

/**
 * StatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusRepository extends \Doctrine\ORM\EntityRepository
{
    public function getStatus(){
        $qb = $this->_em->createQueryBuilder();
        $qb ->from('TicketBundle:Status', 'status')
            ->select ('status');
        return $qb->getQuery()->getResult();
    }
}
