<?php

namespace TicketBundle\Repository;

use Doctrine\Common\Collections\Criteria;

/**
 * TicketUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketUserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUsers($param){
        $exp = Criteria::expr();
        $criteria = Criteria::create()->where($exp->gte('ticket_user.id', 1));
        if(isset($param['name']) && !empty($param['name'])){
            $criteria->andWhere($exp->contains('ticket_user.name', $param['name']));
        }
        if(isset($param['valid']) && !empty($param['valid'])){
            $criteria->andWhere($exp->eq('ticket_user.valid', $param['valid']));
        }
        $qb = $this->_em->createQueryBuilder();
        $qb ->from('TicketBundle:TicketUser', 'ticket_user')
            ->select ('ticket_user.id,
                      ticket_user.valid,
                      ticket_user.email,
                      ticket_user.name')
            ->addCriteria($criteria);
        return $qb->getQuery()->getResult();
    }
}
